apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: yumol/hashgen
  newTag: 8ccd23da86746f26dac1eeda360c773ae261a689
